# SPDX-License-Identifier: AGPL-3.0-or-later
# Optional report helpers for Zendure Energy Controller CSV analysis.

import html
import json
import re
from typing import Any, Dict, Iterable, List, Tuple


class SafeHtml(str):
    """Small marker for trusted HTML snippets generated by this module."""


TERM_HELP: Dict[str, str] = {
    "Dateien": "CSV-Dateien, die in diesen Analyselauf eingeflossen sind. Die Analyse betrachtet nur diese Auswahl, nicht die gesamte Historie.",
    "Datenzeilen": "Anzahl ausgewerteter Messpunkte nach Schema- und Größenprüfung.",
    "Zeitraum": "Erster bis letzter Zeitstempel der ausgewerteten Messdaten.",
    "Dauer": "Zeitspanne zwischen erstem und letztem Messpunkt.",
    "Datenqualität": "Gesamtbewertung der Verwendbarkeit der ausgewählten Messdaten für die Analyse.",
    "Status": "Kurzbewertung der Datenqualität. Warnungen werden separat aufgeführt.",
    "Datenlücken": "Anzahl erkannter größerer Zeitabstände zwischen Messpunkten.",
    "Fehlende Netzwerte": "Messpunkte ohne auswertbare Netzleistung. Diese Werte sind für die Reglerqualitätsbewertung kritisch.",
    "Fehlende SOC-Werte": "Messpunkte ohne Zendure-SOC. SOC-bezogene Auswertungen sind dann nur eingeschränkt belastbar.",
    "Fehlende Zendure-Istwerte": "Messpunkte ohne reale Zendure-Istleistung. Soll-/Ist-Vergleiche sind dann eingeschränkt.",
    "SAFE_STATE-Zeit": "Ausgewertete Zeit, in der der Controller laut CSV im Safe-State war.",
    "Netzbezug": "Aus positiver Netzleistung integrierte Energie. Bezieht sich nur auf die ausgewählten CSV-Dateien.",
    "Netzeinspeisung": "Aus negativer Netzleistung integrierte Energie. Bezieht sich nur auf die ausgewählten CSV-Dateien.",
    "Zendure geladen": "Aus positiver signierter Zendure-Istleistung berechnete Ladeenergie.",
    "Zendure entladen": "Aus negativer signierter Zendure-Istleistung berechnete Entladeenergie.",
    "Zusatzbatterie geladen": "Aus positiver Zusatzbatterie-Leistung berechnete Ladeenergie, sofern die Werte vorhanden sind.",
    "Zusatzbatterie entladen": "Aus negativer Zusatzbatterie-Leistung berechnete Entladeenergie, sofern die Werte vorhanden sind.",
    "Gesamte Ø |Netz|": "Mittlere absolute Netzabweichung über den gesamten Analysezeitraum. Enthält auch volle Batterie, Safe-State und Leistungsgrenzen und ist daher keine reine Reglerbewertung.",
    "Regelbares Zeitfenster": "Zeitanteil, in dem der Controller grundsätzlich eine sinnvolle Stellmöglichkeit hatte oder das Netz bereits im Zielband lag.",
    "Beeinflussbare Ø Restabweichung": "Nur der Anteil der Netzabweichung, der nach verfügbarer Lade-/Entladereserve theoretisch beeinflussbar war.",
    "Beeinflussbare Ø aktiv": "Beeinflussbare Restabweichung bezogen auf das aktive Regelfenster. Diese Kennzahl ist die fairere Reglerqualitätsgröße.",
    "Nicht beeinflussbare Ø Abweichung": "Abweichungsanteil, der wegen SOC-/Leistungsgrenzen, Safe-State oder fehlender Stellreserve nicht vom Regler beseitigt werden konnte.",
    "Nicht beeinflussbarer Anteil": "Anteil der gewichteten Gesamtabweichung, der in diesem Analyselauf nicht sinnvoll dem Regleralgorithmus zugerechnet werden sollte.",
    "Ladelimit-Zeit": "Zeit mit Einspeisung, in der keine oder fast keine zusätzliche Ladereserve verfügbar war.",
    "Entladelimit-Zeit": "Zeit mit Netzbezug, in der keine oder fast keine zusätzliche Entladereserve verfügbar war.",
    "Ø freie Ladereserve": "Durchschnittlich verfügbare zusätzliche Ladeleistung während einspeisender Phasen mit vorhandener Stellreserve.",
    "Ø freie Entladereserve": "Durchschnittlich verfügbare zusätzliche Entladeleistung während bezugslastiger Phasen mit vorhandener Stellreserve.",
    "Ø Soll/Ist-Abweichung": "Mittlere Differenz zwischen signierter Zendure-Sollleistung und signierter Istleistung bei aktiver Anforderung.",
    "Ziel gut erreicht": "Zeitanteil, in dem Zendure dem Sollwert innerhalb einer tolerierten Abweichung folgte.",
    "Ziel deutlich verfehlt": "Zeitanteil, in dem die Soll-/Ist-Abweichung deutlich erhöht war.",
    "Anforderung ohne Reaktion": "Zeit mit relevanter Lade- oder Entladeanforderung, aber kaum entsprechender Zendure-Istleistung.",
    "Sollwert-Richtungswechsel": "Anzahl der Vorzeichenwechsel des Sollwerts zwischen Laden und Entladen. Viele Wechsel können auf Oszillation hinweisen.",
    "Kurze Gegenbefehle": "Richtungswechsel innerhalb kurzer Zeit. Das kann auf eine zu aggressive oder zu wenig gedämpfte Regelung hinweisen.",
    "Große Sollwertsprünge": "Anzahl großer Änderungen des Sollwerts. Einzelne Sprünge können normal sein, viele Sprünge deuten auf unruhige Regelung.",
    "Schwingungsbewertung": "Verdichtete Bewertung der Oszillationsindikatoren.",
    "Zeit im Deadband": "Anteil der Zeit, in der die Netzleistung innerhalb des konfigurierten Deadbands lag.",
    "Zeit im erweiterten Zielband": "Anteil der Zeit in einem größeren Zielbereich um 0 W. Hilft, die praktische Regelruhe zu bewerten.",
    "HOLD korrekt im Deadband": "Zeitanteil, in dem der Regler im Deadband sinnvoll keine Stelländerung vorgenommen hat.",
    "Außerhalb Deadband mit Reserve": "Zeit außerhalb des Deadbands, obwohl noch Stellreserve vorhanden war. Das ist ein Kandidat für echte Reglerabweichung.",
    "Kommandos im Deadband": "MQTT-Kommandos, obwohl das Netz bereits im Deadband lag. Viele davon können unnötige Unruhe bedeuten.",
    "MQTT-Kommandos gesamt": "Anzahl gesendeter MQTT-Befehle im Analysezeitraum.",
    "Kommandos pro aktiver Regelstunde": "MQTT-Kommandos bezogen auf das aktive Regelfenster, nicht auf den gesamten Logzeitraum.",
    "Erkennbare Verbesserung": "Anteil bewertbarer Kommandos, nach denen die absolute Netzabweichung wenige Zyklen später kleiner war. Diese Diagnose ist grob, da Last/PV parallel schwanken.",
    "Keine erkennbare Wirkung": "Anteil bewertbarer Kommandos ohne deutliche Verbesserung oder Verschlechterung wenige Zyklen später.",
    "Ampel": "Verdichtete Cross-Charge-Bewertung: grün unauffällig, gelb kurze/geringe Überschneidungen, rot deutliche kritische Überschneidungen.",
    "Bewertung": "Textliche Begründung für die Ampelfarbe.",
    "Blockade-Ereignisse": "Anzahl erkannter Phasen, in denen Cross-Charge-Begrenzungen oder -Blockaden aktiv waren.",
    "Blockade-Zeit": "Gesamtdauer der erkannten Cross-Charge-Blockadephasen.",
    "Kritische Überschneidungen": "Phasen, in denen die Zusatzbatterie entlädt, während Zendure gleichzeitig lädt.",
    "Zeit bei MIN_SOC": "Zeit, in der der Zendure-SOC am unteren konfigurierten Grenzwert lag.",
    "Zeit bei MAX_SOC": "Zeit, in der der Zendure-SOC am oberen konfigurierten Grenzwert lag.",
    "High-SOC-Ladeannahme": "Verteilung der einfachen Ladeannahme-Diagnosezustände. V12.8.4 wertet diesen Bereich nur leichtgewichtig aus.",
    "Zustand": "Abgeleiteter Betriebszustand für die Matrix. Er trennt regelbare und nicht regelbare Phasen besser als der reine technische Modus.",
    "Samples": "Anzahl der Messpunkte, die dieser Zeile zugeordnet wurden.",
    "Zeit": "Aus dt_s aufsummierte Dauer für diese Gruppe oder dieses Ereignis.",
    "Zielband": "Anteil der Zeit, in der die Netzleistung innerhalb des Zielbandes um 0 W lag.",
    "MQTT": "Anzahl der in diesem Bereich gesendeten MQTT-Kommandos.",
    "Schwere": "Einordnung des Ereignisses, z. B. Info, Warnung oder kritisch.",
    "Typ": "Technische Ereigniskategorie für Filterung und spätere Auswertung.",
    "Ereignis": "Lesbare Beschreibung der erkannten Auffälligkeit oder Zustandsänderung.",
}

TERM_HELP.update({
    "Ampel": "Verdichtete Ampelbewertung des jeweiligen Analyseblocks. Die Bedeutung hängt vom Block ab: Bei Reglerqualität geht es um beeinflussbare Netzabweichung, bei MQTT um erkennbare Kommandowirkung, bei Cross-Charge um kritische Überschneidungen zwischen Zusatzbatterie und Zendure.",
    "Kurzfazit": "Gesamturteil über den ausgewählten Analysezeitraum. Es soll zuerst beantworten, ob Handlungsdruck besteht oder ob das System weitgehend unauffällig arbeitet.",
    "Handlungsdruck": "Abgestufte Einschätzung, ob aus der Analyse konkrete Maßnahmen folgen sollten. Hoher Handlungsdruck entsteht vor allem durch schlechte Datenqualität, ineffiziente Regelung oder kritisches Cross-Charge-Verhalten.",
    "Soll/Ist": "Vergleich zwischen angeforderter Zendure-Leistung und tatsächlich gemessener Zendure-Leistung. Große Abweichungen können durch SOC, Temperatur, Zendure-interne Limits oder veraltete Telemetrie entstehen.",
    "Deadband": "Totzone um 0 W Netzleistung. Innerhalb dieser Zone soll der Regler bewusst ruhig bleiben, damit kleine Mess- und Lastschwankungen nicht ständig neue MQTT-Kommandos auslösen.",
    "MQTT-Wirkung": "Grobe Diagnose, ob gesendete Leistungsbefehle wenige Messzyklen später eine kleinere absolute Netzabweichung bewirken. Die Bewertung ist nicht kausal beweisend, weil PV und Hauslast gleichzeitig schwanken können.",
    "Nicht bewertbar": "Der Effekt konnte nicht belastbar beurteilt werden, z. B. wegen Safe-State, fehlenden Folgemesspunkten, Datenlücken oder stark überlagernden Last-/PV-Sprüngen.",
    "Ø / Median / max dt_s": "Zeitabstand der Messpunkte. Der Median beschreibt den typischen Takt, der Maximalwert zeigt Datenlücken oder Hänger. Große dt_s-Werte reduzieren die Belastbarkeit der Analyse.",
    "95%-Perzentil Soll/Ist-Abweichung": "95 Prozent der betrachteten Soll-/Ist-Abweichungen liegen unterhalb dieses Betrags. Robuster als der Maximalwert, weil einzelne Ausreißer weniger dominieren.",
    "Kritische Überschneidungszeit": "Gesamtdauer, in der die Zusatzbatterie entlädt und Zendure gleichzeitig lädt. Das ist im Systemkontext unerwünscht, weil Energie zwischen Speichern umgeladen werden kann.",
    "Max. SMA-Entladung während Überschneidung": "Höchste erkannte Entladeleistung der Zusatzbatterie während gleichzeitiger Zendure-Ladung.",
    "Ø SMA-Entladung während Überschneidung": "Durchschnittliche Entladeleistung der Zusatzbatterie während kritischer Cross-Charge-Phasen.",
    "Max. Zendure-Ladung während Überschneidung": "Höchste Zendure-Ladeleistung während die Zusatzbatterie gleichzeitig entlädt.",
    "Verhinderte/reduzierte Ladeenergie grob": "Grob integrierte Energie, die durch Cross-Charge-Begrenzung nicht oder reduziert in Zendure geladen wurde. Der Wert hilft, den Nutzen des Schutzes einzuordnen.",
    "Moduswechsel": "Anzahl der Wechsel zwischen technischen Betriebsmodi. Viele Wechsel pro Stunde können auf instabile Randbedingungen oder zu aggressive Parameter hindeuten.",
    "Beeinflussbar Ø": "Mittlere Restabweichung, die in diesem Zustand theoretisch durch Zendure-Stellleistung beeinflussbar war.",
    "Nicht beeinflussbar Ø": "Mittlere Abweichung, die wegen SOC-, Leistungs-, Safe-State- oder Datenlimits nicht sinnvoll dem Regler zugerechnet werden sollte.",
    "Hinweise": "Datenqualitäts- und Analysehinweise. Diese Meldungen erklären, warum bestimmte Kennzahlen nur eingeschränkt belastbar sind.",
})

TERM_HELP.update({
    "Abweichungsursachen": "Dieses Diagramm klassifiziert gewichtete Netzabweichungen danach, ob der Controller im jeweiligen Zustand theoretisch gegensteuern konnte. Die Werte werden als Prozentanteil der gewichteten Abweichung angezeigt.",
    "Beeinflussbar": "Im Controller-Kontext bedeutet das: Zendure hatte im jeweiligen Zustand grundsätzlich Stellmöglichkeit und hätte die Netzabweichung theoretisch reduzieren können. Es heißt nicht automatisch, dass der Benutzer nur einen Parameter ändern muss.",
    "Nicht beeinflussbar": "Abweichungen, die wegen SOC-Grenze, Leistungsgrenze, Safe-State, fehlender Daten oder anderer Randbedingungen nicht sinnvoll dem Regleralgorithmus zugerechnet werden sollten.",
    "Betriebszustände": "Dieses Diagramm zeigt, wie lange der Controller in den wichtigsten abgeleiteten Betriebszuständen war. Angezeigt wird Dauer plus Prozentanteil am analysierten Zeitraum.",
    "SAFE_STATE": "Sicherheitszustand. Der Controller begrenzt oder stoppt Stellbefehle, weil eine erforderliche Datenquelle oder Bedingung nicht belastbar ist.",
    "HOLD_DEADBAND": "Haltezustand im Deadband. Die Netzabweichung liegt im Toleranzbereich, daher vermeidet der Controller unnötige neue Kommandos.",
    "AUTO_DISCHARGE": "Automatikbetrieb mit Entladeanforderung an Zendure, um Netzbezug zu reduzieren.",
    "AUTO_CHARGE": "Automatikbetrieb mit Ladeanforderung an Zendure, um Einspeisung zu reduzieren.",
    "Verbessert": "Einige Messzyklen nach einem MQTT-Kommando war die absolute Netzabweichung kleiner. Das ist ein Hinweis auf wirksame Regelung, aber kein harter Kausalbeweis, weil PV und Hauslast parallel schwanken können.",
    "Neutral": "Nach dem MQTT-Kommando war keine eindeutige Verbesserung oder Verschlechterung erkennbar.",
    "Verschlechtert": "Einige Messzyklen nach einem MQTT-Kommando war die absolute Netzabweichung größer. Einzelne Fälle können durch Last-/PV-Sprünge entstehen; Häufung wäre auffällig.",
    "Anzahl": "Absolute Anzahl von Messpunkten, Kommandos oder Ereignissen. Für die Interpretation ist die jeweilige Basis wichtig.",
    "Anteil": "Prozentanteil bezogen auf die im jeweiligen Block genannte Basis, z. B. bewertbare Kommandos oder analysierte Zeitdauer.",
})

TERM_HELP.update({
    "NIGHT_DISCHARGE": "Feste Nacht-Basisentladung. Der Controller fordert im Nachtfenster eine konstante Entladeleistung an. Seit V12.8.17 bedeutet ein erreichter Nachtmodus-Reserve-SOC: nur diese feste Basisentladung pausiert; AUTO kann Lastspitzen weiterhin ausregeln.",
    "HOLD_OUTSIDE_DEADBAND": "Haltezustand außerhalb des Deadbands. Der Controller sendet in diesem Moment kein neues Kommando, z. B. weil Mindeständerung, Sperrzeit, Grenzen oder andere Schutzlogik eine Änderung verhindern.",
    "CROSS_CHARGE_BLOCK": "Cross-Charge-Schutz blockiert oder reduziert Zendure-Ladung, weil die Zusatzbatterie/SMA-Quelle entlädt oder nicht genügend echter Überschuss vorhanden ist.",
    "CROSS_CHARGE_LIMIT": "Cross-Charge-Schutz begrenzt Zendure-Ladung, um Batterie-zu-Batterie-Ladung zu vermeiden.",
    "CROSS_CHARGE": "Cross-Charge-bezogener Betriebszustand. Diese Zustände zeigen, dass der Schutz gegen gleichzeitige Zusatzbatterie-Entladung und Zendure-Ladung relevant war.",
    "verbessert": "Einige Messzyklen nach einem MQTT-Kommando war die absolute Netzabweichung kleiner. Das ist ein Hinweis auf wirksame Regelung, aber kein harter Kausalbeweis.",
    "neutral": "Nach dem MQTT-Kommando war keine eindeutige Verbesserung oder Verschlechterung der absoluten Netzabweichung erkennbar.",
    "verschlechtert": "Einige Messzyklen nach einem MQTT-Kommando war die absolute Netzabweichung größer. Einzelne Fälle können durch Last-/PV-Sprünge entstehen; Häufung wäre auffällig.",
    "nicht bewertbar": "Das Kommando konnte nicht belastbar bewertet werden, z. B. wegen fehlender Folgemesspunkte, Datenlücken, Safe-State oder stark überlagernden Last-/PV-Sprüngen.",
})

try:
    from version import APP_VERSION as REPORT_VERSION
except Exception:  # pragma: no cover
    REPORT_VERSION = "12.8.9"


def _duration(seconds: float) -> str:
    seconds = int(float(seconds or 0))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h} h {m:02d} min"
    if m:
        return f"{m} min {s:02d} s"
    return f"{s} s"


def _format_de_number(value: Any, digits: int = 1, *, trim: bool = True) -> str:
    if value in (None, ""):
        return "-"
    try:
        number = float(value)
    except Exception:
        return str(value)
    text = f"{number:,.{max(0, digits)}f}"
    if trim and digits > 0:
        text = text.rstrip("0").rstrip(".")
    return text.replace(",", "X").replace(".", ",").replace("X", ".")


def _num(value: Any, suffix: str = "", digits: int = 1, *, trim: bool = True) -> str:
    return f"{_format_de_number(value, digits, trim=trim)}{suffix}"


def _kwh(value: Any) -> str: return _num(value, " kWh", 4, trim=False)
def _w(value: Any) -> str: return _num(value, " W", 1, trim=True)
def _pct(value: Any) -> str: return _num(value, " %", 1, trim=True)
def _per_hour(value: Any) -> str: return _num(value, " / h", 1, trim=True)

def _count(value: Any, label: str = "") -> str:
    try:
        number = int(round(float(value or 0)))
    except Exception:
        number = 0
    suffix = f" {label}" if label else ""
    return f"{_format_de_number(number, 0)}{suffix}"

def _pct_with_basis(percent: Any, basis: Any = None) -> str:
    if basis not in (None, ""):
        return f"{_pct(percent)} von {_format_de_number(basis, 0)}"
    return _pct(percent)

def _duration_with_percent(seconds: Any, percent: Any = None) -> str:
    if percent is None:
        return _duration(seconds)
    return f"{_duration(seconds)} ({_pct(percent)})"


def _states_summary(states: Dict[str, Any]) -> str:
    order = ["ok", "suspect", "limited", "not_accepting"]
    labels = {"ok": "ok", "suspect": "Verdacht", "limited": "begrenzt", "not_accepting": "nimmt nicht an"}
    parts = [f"{labels[k]}: {states.get(k, 0)}" for k in order if k in states]
    parts += [f"{k}: {states.get(k, 0)}" for k in sorted(k for k in states if k not in order)]
    return ", ".join(parts) if parts else "keine Daten"


def _stringify_mapping(value: Dict[str, Any]) -> str:
    if set(value.keys()) & {"ok", "suspect", "limited", "not_accepting"}:
        return _states_summary(value)
    return ", ".join(f"{key}: {val}" for key, val in sorted(value.items()))


def _label_cell(label: str) -> SafeHtml:
    label_text = str(label)
    help_text = TERM_HELP.get(label_text)
    escaped = html.escape(label_text)
    if not help_text:
        return SafeHtml(f"<div class='label-main'>{escaped}</div>")
    return SafeHtml(f"<div class='label-main'>{escaped}</div><details class='term-info'><summary>info</summary><div>{html.escape(help_text)}</div></details>")


def _cell(value: Any) -> str:
    if isinstance(value, SafeHtml):
        return str(value)
    if isinstance(value, dict):
        return html.escape(_stringify_mapping(value))
    if isinstance(value, (list, tuple)):
        return html.escape(", ".join(_stringify_mapping(v) if isinstance(v, dict) else str(v) for v in value))
    return html.escape(str(value))


def _table(rows: Iterable[Tuple[str, Any]]) -> str:
    return "".join(f"<tr><th>{_label_cell(str(label))}</th><td>{_cell(value)}</td></tr>" for label, value in rows)


def _th(label: str) -> str: return str(_label_cell(label))


def _rating_badge(value: str) -> SafeHtml:
    cls = {"green": "ok", "yellow": "warn", "amber": "warn", "red": "bad", "ok": "ok", "warning": "warn", "error": "bad", "gray": "neutral", "grey": "neutral", "-": "neutral"}.get(str(value), "neutral")
    label = {"green": "grün", "yellow": "gelb", "amber": "gelb", "red": "rot", "ok": "ok", "warning": "Warnung", "error": "Fehler", "gray": "nicht bewertbar", "grey": "nicht bewertbar", "-": "nicht bewertbar"}.get(str(value), str(value))
    return SafeHtml(f"<span class='badge {cls}'>{html.escape(label)}</span>")


def _bar(label: str, value: float, max_value: float, css: str = "bar") -> SafeHtml:
    width = 0 if max_value <= 0 else max(0.0, min(100.0, float(value) / max_value * 100.0))
    return SafeHtml(f"<div class='barrow'><span>{html.escape(label)}</span><div class='barbox'><div class='{css}' style='width:{width:.1f}%'></div></div><b>{_format_de_number(value, 1)}</b></div>")


def _bars(items: List[Tuple[str, float]], css: str = "bar") -> SafeHtml:
    if not items:
        return SafeHtml("<p>Keine Diagrammdaten.</p>")
    max_value = max([abs(float(v or 0)) for _, v in items] + [1.0])
    return SafeHtml("".join(str(_bar(label, float(value or 0), max_value, css)) for label, value in items))


def _rating_score(value: str) -> int:
    return {"green": 0, "ok": 0, "yellow": 1, "warning": 1, "red": 2, "error": 2}.get(str(value), 1)


def overall_verdict(result: Dict[str, Any]) -> Dict[str, str]:
    ratings = result.get("summary_ratings") or {}
    dq = (result.get("data_quality") or {}).get("status", "ok")
    recs = result.get("recommendations") or []
    scores = [_rating_score(v) for v in ratings.values()] or [1]
    red_count = sum(1 for score in scores if score >= 2)
    yellow_count = sum(1 for score in scores if score == 1)
    non_controllable = float((result.get("fair_regulator_quality") or {}).get("non_controllable_percent", 0) or 0)
    controllable_avg = float((result.get("fair_regulator_quality") or {}).get("controllable_active_avg_abs_grid_w", 0) or 0)
    cross_rating = str((result.get("cross_charge") or {}).get("rating", "green"))

    if dq != "ok":
        title = "Datenbasis zuerst prüfen"
        pressure = "mittlerer bis hoher Handlungsdruck"
        text = "Die ausgewählten Messdaten enthalten Lücken oder fehlende Werte. Bevor Parameter angepasst werden, sollte zuerst die Datenqualität verbessert oder ein belastbarerer Zeitraum analysiert werden."
        rating = "yellow"
    elif red_count >= 2 or cross_rating == "red":
        title = "Dringender Handlungsbedarf"
        pressure = "hoch"
        text = "Mehrere Kernbereiche sind kritisch oder Cross-Charge ist deutlich auffällig. Die Regelung bzw. Randbedingungen sollten gezielt geprüft werden."
        rating = "red"
    elif red_count == 1 or yellow_count >= 3 or controllable_avg > 300:
        title = "Mittlerer Handlungsbedarf"
        pressure = "mittel"
        text = "Die Anlage arbeitet nicht grundsätzlich falsch, aber die Analyse zeigt relevante Ansatzpunkte. Priorisiere die Handlungsempfehlungen und prüfe die betroffenen Zeiträume genauer."
        rating = "yellow"
    elif non_controllable > 60:
        title = "Geringer Regler-Handlungsbedarf"
        pressure = "gering"
        text = "Ein großer Teil der Abweichungen war systembedingt nicht beeinflussbar. Mehr Reglerfeintuning bringt wahrscheinlich wenig; eher SOC-/Leistungsgrenzen und Kapazität betrachten."
        rating = "green"
    else:
        title = "Läuft sehr gut / unauffällig"
        pressure = "gering"
        text = "Die ausgewählten Daten zeigen keine gravierenden Auffälligkeiten. Beobachten reicht; Parameteränderungen sind aus diesem Zeitraum nicht zwingend ableitbar."
        rating = "green"

    if recs:
        first = recs[0]
        text += " Wichtigster Hinweis: " + str(first.get("topic", "-")) + " – " + str(first.get("text", "-"))
    return {"title": title, "pressure": pressure, "text": text, "rating": rating}


def overall_verdict_html(result: Dict[str, Any]) -> SafeHtml:
    verdict = overall_verdict(result)
    return SafeHtml(
        "<div class='verdict'>"
        f"<h3>{html.escape(verdict['title'])} {_rating_badge(verdict['rating'])}</h3>"
        f"<p><b>Handlungsdruck:</b> {html.escape(verdict['pressure'])}</p>"
        f"<p>{html.escape(verdict['text'])}</p>"
        "</div>"
    )


def summary_cards(result: Dict[str, Any]) -> str:
    ratings = result.get("summary_ratings") or {}
    labels = [
        ("fair_regulator_quality", "Reglerqualität"), ("actuator_reserve", "Stellreserve"),
        ("zendure_tracking", "Soll/Ist"), ("deadband", "Deadband"),
        ("mqtt_command_effect", "MQTT-Wirkung"), ("oscillation", "Oszillation"),
        ("cross_charge", "Cross-Charge"), ("data_quality", "Datenqualität"),
    ]
    cards = []
    for key, label in labels:
        cards.append(f"<div class='card'><div>{html.escape(label)}</div>{_rating_badge(str(ratings.get(key, '-')))}</div>")
    return "".join(cards)


def recommendations_table(result: Dict[str, Any]) -> str:
    recs = result.get("recommendations") or []
    if not recs:
        return "<tr><td>Keine Empfehlungen erzeugt.</td></tr>"
    rows = f"<tr><th>{_th('Schwere')}</th><th>Thema</th><th>Empfehlung</th></tr>"
    for rec in recs:
        rows += f"<tr><td>{_rating_badge(str(rec.get('severity','neutral')))}</td><td>{html.escape(str(rec.get('topic','-')))}</td><td>{html.escape(str(rec.get('text','-')))}</td></tr>"
    return rows


def overview_table(result: Dict[str, Any]) -> str:
    dq = result.get("data_quality") or {}
    return _table([
        ("Dateien", ", ".join(result.get("filenames") or [result.get("filename", "-")])),
        ("Datenzeilen", result.get("rows", 0)),
        ("Zeitraum", f"{result.get('period_start', '-')} bis {result.get('period_end', '-')}"),
        ("Dauer", _duration(result.get("duration_seconds", 0))),
        ("Datenqualität", _rating_badge("green" if dq.get("status") == "ok" else ("red" if dq.get("status") == "error" else "yellow"))),
        ("Ø / Median / max dt_s", f"{_num(dq.get('avg_dt_s', 0), '', 3)} / {_num(dq.get('median_dt_s', 0), '', 3)} / {_num(dq.get('max_dt_s', 0), ' s', 3)}"),
    ])



def _row_pct(count: Any, total: Any) -> str:
    try:
        total_i = int(total or 0)
        count_i = int(count or 0)
    except Exception:
        return "-"
    if total_i <= 0:
        return "-"
    return _pct(count_i * 100.0 / total_i)


def _data_quality_facts(result: Dict[str, Any]) -> List[str]:
    dq = result.get("data_quality") or {}
    rows = int(result.get("rows") or 0)
    duration = float(result.get("duration_seconds") or 0)
    facts: List[str] = []
    gap_events = int(dq.get("gap_events") or 0)
    missing_grid = int(dq.get("missing_grid_rows") or 0)
    missing_soc = int(dq.get("missing_soc_rows") or 0)
    missing_actual = int(dq.get("missing_zendure_actual_rows") or 0)
    safe_s = float(dq.get("safe_state_seconds") or 0)
    if gap_events:
        facts.append(f"{gap_events} größere Zeitlücken")
    if missing_grid:
        facts.append(f"{missing_grid} Zeilen ohne Netzleistung ({_row_pct(missing_grid, rows)} der Zeilen)")
    if missing_soc:
        facts.append(f"{missing_soc} Zeilen ohne Zendure-SOC ({_row_pct(missing_soc, rows)} der Zeilen)")
    if missing_actual:
        facts.append(f"{missing_actual} Zeilen ohne Zendure-Istleistung ({_row_pct(missing_actual, rows)} der Zeilen)")
    if safe_s > 0:
        facts.append(f"SAFE_STATE {_duration(safe_s)} ({_pct(safe_s * 100.0 / duration) if duration > 0 else '-'})")
    duplicate_rows = int(result.get("duplicate_rows_removed") or 0)
    if duplicate_rows:
        facts.append(f"{duplicate_rows} doppelte Messpunkte entfernt")
    return facts


def _data_quality_recommendation_text(result: Dict[str, Any]) -> str:
    facts = _data_quality_facts(result)
    if not facts:
        return "Datenbasis ist eingeschränkt; Details im Block Datenqualität prüfen."
    return "Datenbasis eingeschränkt: " + "; ".join(facts[:4]) + ". Betroffene Auswertungen sind je nach fehlendem Feld eingeschränkt; Details im Block Datenqualität."

def data_quality_table(result: Dict[str, Any]) -> str:
    dq = result.get("data_quality") or {}
    rows = int(result.get("rows") or 0)
    duration = float(result.get("duration_seconds") or 0)
    warnings = dq.get("warnings") or []
    facts = _data_quality_facts(result)
    warning_html = SafeHtml("<br>".join(html.escape(str(w)) for w in warnings)) if warnings else "keine"
    if facts:
        summary = SafeHtml("<b>Gefunden:</b><br>" + "<br>".join(html.escape(f) for f in facts) + "<br><br><b>Einordnung:</b> " + html.escape(_data_quality_recommendation_text(result)))
    else:
        summary = SafeHtml("Keine relevanten Datenlücken oder fehlenden Pflichtwerte erkannt.")
    safe_s = float(dq.get("safe_state_seconds") or 0)
    return _table([
        ("Status", dq.get("status", "-")),
        ("Zusammenfassung", summary),
        ("Datenlücken", dq.get("gap_events", 0)),
        ("Fehlende Netzwerte", f"{dq.get('missing_grid_rows', 0)} von {rows} Zeilen ({_row_pct(dq.get('missing_grid_rows', 0), rows)})"),
        ("Fehlende SOC-Werte", f"{dq.get('missing_soc_rows', 0)} von {rows} Zeilen ({_row_pct(dq.get('missing_soc_rows', 0), rows)})"),
        ("Fehlende Zendure-Istwerte", f"{dq.get('missing_zendure_actual_rows', 0)} von {rows} Zeilen ({_row_pct(dq.get('missing_zendure_actual_rows', 0), rows)})"),
        ("SAFE_STATE-Zeit", f"{_duration(safe_s)} ({_pct(safe_s * 100.0 / duration) if duration > 0 else '-'})"),
        ("Hinweise", warning_html),
    ])


def energy_table(result: Dict[str, Any]) -> str:
    e = result.get("energy") or {}
    return _table([
        ("Netzbezug", _kwh(e.get('grid_import_kwh', result.get('grid_import_kwh', 0)))),
        ("Netzeinspeisung", _kwh(e.get('grid_export_kwh', result.get('grid_export_kwh', 0)))),
        ("Zendure geladen", _kwh(e.get('zendure_charge_kwh', 0))), ("Zendure entladen", _kwh(e.get('zendure_discharge_kwh', 0))),
        ("Zusatzbatterie geladen", _kwh(e.get('second_battery_charge_kwh', 0))), ("Zusatzbatterie entladen", _kwh(e.get('second_battery_discharge_kwh', 0))),
    ])


def fair_regulator_table(result: Dict[str, Any]) -> str:
    fq = result.get("fair_regulator_quality") or {}
    return _table([
        ("Ampel", _rating_badge(str(fq.get("rating", "-")))),
        ("Gesamte Ø |Netz|", _w(fq.get("total_avg_abs_grid_w", 0))),
        ("Regelbares Zeitfenster", f"{_duration(fq.get('active_window_seconds', 0))} ({_pct(fq.get('active_window_percent', 0))})"),
        ("Beeinflussbare Ø Restabweichung", _w(fq.get("controllable_avg_abs_grid_w", 0))),
        ("Beeinflussbare Ø aktiv", _w(fq.get("controllable_active_avg_abs_grid_w", 0))),
        ("Nicht beeinflussbare Ø Abweichung", _w(fq.get("non_controllable_avg_abs_grid_w", 0))),
        ("Nicht beeinflussbarer Anteil", _pct(fq.get("non_controllable_percent", 0))),
    ])


def actuator_table(result: Dict[str, Any]) -> str:
    ar = result.get("actuator_reserve") or {}
    return _table([
        ("Ampel", _rating_badge(str(ar.get("rating", "-")))),
        ("Ladelimit-Zeit", f"{_duration(ar.get('charge_saturated_seconds', 0))} ({_pct(ar.get('charge_saturated_percent', 0))})"),
        ("Entladelimit-Zeit", f"{_duration(ar.get('discharge_saturated_seconds', 0))} ({_pct(ar.get('discharge_saturated_percent', 0))})"),
        ("Ø freie Ladereserve", _w(ar.get("avg_free_charge_reserve_w", 0))),
        ("Ø freie Entladereserve", _w(ar.get("avg_free_discharge_reserve_w", 0))),
    ])


def tracking_table(result: Dict[str, Any]) -> str:
    tr = result.get("tracking") or {}
    return _table([
        ("Ampel", _rating_badge(str(tr.get("rating", "-")))),
        ("Ø Soll/Ist-Abweichung", _w(tr.get("avg_error_w", 0))),
        ("95%-Perzentil Soll/Ist-Abweichung", _w(tr.get("p95_error_w", 0))),
        ("Ziel gut erreicht", _pct(tr.get("good_tracking_percent", 0))),
        ("Ziel deutlich verfehlt", _pct(tr.get("bad_tracking_percent", 0))),
        ("Anforderung ohne Reaktion", _duration(tr.get("target_without_actual_seconds", 0))),
    ])


def oscillation_table(result: Dict[str, Any]) -> str:
    osc = result.get("oscillation") or {}
    return _table([
        ("Schwingungsbewertung", _rating_badge(str(osc.get("rating", "-")))),
        ("Sollwert-Richtungswechsel", osc.get("target_sign_changes", 0)),
        ("Kurze Gegenbefehle", osc.get("short_reverse_commands", 0)),
        ("Große Sollwertsprünge", osc.get("large_target_steps", 0)),
        ("Moduswechsel", f"{osc.get('mode_switches', 0)} ({_per_hour(osc.get('mode_switches_per_hour', 0))})"),
    ])


def deadband_table(result: Dict[str, Any]) -> str:
    db = result.get("deadband") or {}
    return _table([
        ("Ampel", _rating_badge(str(db.get("rating", "-")))),
        ("Zeit im Deadband", f"{_duration(db.get('inside_deadband_seconds', 0))} ({_pct(db.get('inside_deadband_percent', 0))})"),
        ("Zeit im erweiterten Zielband", f"{_duration(db.get('inside_extended_band_seconds', 0))} ({_pct(db.get('inside_extended_band_percent', 0))})"),
        ("HOLD korrekt im Deadband", _pct(db.get("hold_inside_deadband_percent", 0))),
        ("Außerhalb Deadband mit Reserve", f"{_duration(db.get('outside_deadband_with_reserve_seconds', 0))} ({_pct(db.get('outside_deadband_with_reserve_percent', 0))})"),
        ("Kommandos im Deadband", db.get("commands_inside_deadband", 0)),
    ])


def command_efficiency_table(result: Dict[str, Any]) -> str:
    ce = result.get("command_efficiency") or {}
    return _table([
        ("Ampel", _rating_badge(str(ce.get("rating", "-")))),
        ("MQTT-Kommandos gesamt", ce.get("commands_total", 0)),
        ("Kommandos pro aktiver Regelstunde", _per_hour(ce.get("commands_per_active_hour", 0))),
        ("Ø / max Sollwertsprung", f"{_w(ce.get('avg_target_step_w', 0))} / {_w(ce.get('max_target_step_w', 0))}"),
        ("Erkennbare Verbesserung", f"{_count(ce.get('improved_count', 0), 'Kommandos')} ({_pct(ce.get('improved_percent', 0))} der bewertbaren Kommandos)"),
        ("Keine erkennbare Wirkung", f"{_count(ce.get('neutral_count', 0), 'Kommandos')} ({_pct(ce.get('no_effect_percent', 0))} der bewertbaren Kommandos)"),
        ("Nicht bewertbar", f"{_count(ce.get('unknown_count', 0), 'Kommandos')}"),
    ])


def regulator_table(result: Dict[str, Any]) -> str:
    # Compatibility: keep the old table name, but use the new fair view.
    return fair_regulator_table(result)


def cross_charge_table(result: Dict[str, Any]) -> str:
    cq = result.get("cross_charge") or {}
    return _table([
        ("Ampel", _rating_badge(str(cq.get("rating", "-")))), ("Bewertung", cq.get("rating_reason", "-")),
        ("Blockade-Ereignisse", cq.get("block_events", 0)), ("Blockade-Zeit", _duration(cq.get("blocked_seconds", 0))),
        ("Kritische Überschneidungen", cq.get("critical_overlap_events", 0)),
        ("Kritische Überschneidungszeit", _duration(cq.get("critical_overlap_seconds", 0))),
        ("Max. SMA-Entladung während Überschneidung", _w(cq.get('max_sma_discharge_w_during_overlap', 0))),
        ("Ø SMA-Entladung während Überschneidung", _w(cq.get('avg_sma_discharge_w_during_overlap', 0))),
        ("Max. Zendure-Ladung während Überschneidung", _w(cq.get('max_zendure_charge_w_during_overlap', 0))),
        ("Verhinderte/reduzierte Ladeenergie grob", _kwh(cq.get('reduced_or_prevented_charge_kwh', 0))),
    ])


def mode_quality_table(result: Dict[str, Any]) -> str:
    rows = f"<tr><th>{_th('Zustand')}</th><th>{_th('Samples')}</th><th>{_th('Zeit')}</th><th>Import</th><th>Export</th><th>Ø |Netz|</th><th>Beeinflussbar Ø</th><th>Nicht beeinflussbar Ø</th><th>{_th('Zielband')}</th><th>{_th('MQTT')}</th></tr>"
    for item in result.get("operating_state_matrix") or result.get("mode_quality") or []:
        rows += (
            f"<tr><td>{html.escape(str(item.get('mode')))}</td><td>{item.get('samples')}</td><td>{_duration(item.get('seconds', 0))} ({_pct(item.get('percent', 0))})</td>"
            f"<td>{_kwh(item.get('grid_import_kwh', 0))}</td><td>{_kwh(item.get('grid_export_kwh', 0))}</td><td>{_w(item.get('avg_abs_grid_w'))}</td>"
            f"<td>{_w(item.get('controllable_avg_abs_grid_w', 0))}</td><td>{_w(item.get('non_controllable_avg_abs_grid_w', 0))}</td>"
            f"<td>{_pct(item.get('time_in_target_band_percent'))}</td><td>{item.get('mqtt_commands')}</td></tr>"
        )
    return rows


def high_soc_table(result: Dict[str, Any]) -> str:
    states = result.get("charge_acceptance_states") or {}
    return _table([
        ("Zeit bei MIN_SOC", _duration(result.get("time_at_min_soc_seconds", 0))),
        ("Zeit bei MAX_SOC", _duration(result.get("time_at_max_soc_seconds", 0))),
        ("High-SOC-Ladeannahme", _states_summary(states)),
        ("Einordnung", "V12.8.9 zählt High-SOC weiterhin leichtgewichtig; Schwerpunkt sind faire Reglerqualität, Stellreserve und Cross-Charge."),
    ])


def events_table(result: Dict[str, Any], limit: int = 120) -> str:
    events: List[Dict[str, Any]] = list(result.get("events") or [])[:limit]
    if not events:
        return "<tr><td>Keine auffälligen Ereignisse erkannt.</td></tr>"
    rows = f"<tr><th>{_th('Zeit')}</th><th>{_th('Schwere')}</th><th>{_th('Typ')}</th><th>{_th('Ereignis')}</th></tr>"
    for event in events:
        rows += f"<tr><td>{html.escape(str(event.get('time', '-')))}</td><td>{html.escape(str(event.get('severity', '-')))}</td><td>{html.escape(str(event.get('type', '-')))}</td><td>{html.escape(str(event.get('text', '-')))}</td></tr>"
    return rows


def _chart_info(title: str, text: str) -> str:
    return f"<details class='chart-info'><summary>info</summary><div>{html.escape(text)}</div></details>"


def _bar_value(label: str, value_text: str, width_value: float, max_value: float, help_key: str = "", css: str = "bar") -> SafeHtml:
    width = 0 if max_value <= 0 else max(0.0, min(100.0, float(width_value or 0) / max_value * 100.0))
    help_html = ""
    key = help_key or label
    help_text = TERM_HELP.get(key) or TERM_HELP.get(label)
    if not help_text and str(key).startswith("CROSS_CHARGE"):
        help_text = TERM_HELP.get("CROSS_CHARGE")
    if help_text:
        # The details element intentionally sits on the chart row grid itself, not inside
        # the label span. This lets the opened text use the full chart width and keeps
        # label/bar/value columns stable.
        help_html = f"<details class='term-info'><summary>info</summary><div>{html.escape(help_text)}</div></details>"
    return SafeHtml(
        f"<div class='barrow'><span class='barlabel'>{html.escape(label)}</span>"
        f"<div class='barbox'><div class='{css}' style='width:{width:.1f}%'></div></div>"
        f"<b>{html.escape(value_text)}</b>{help_html}</div>"
    )


def _bars_text(items: List[Tuple[str, str, float, str]], css: str = "bar") -> SafeHtml:
    if not items:
        return SafeHtml("<p>Keine Diagrammdaten.</p>")
    max_value = max([abs(float(v or 0)) for _, _, v, _ in items] + [1.0])
    return SafeHtml("".join(str(_bar_value(label, text, width, max_value, help_key, css)) for label, text, width, help_key in items))


def charts_html(result: Dict[str, Any]) -> str:
    fq = result.get("fair_regulator_quality") or {}
    db = result.get("deadband") or {}
    ce = result.get("command_efficiency") or {}
    state_items = []
    for item in (result.get("operating_state_matrix") or [])[:8]:
        seconds = float(item.get("seconds", 0) or 0)
        percent = item.get("percent", 0)
        state_items.append((str(item.get("mode")), f"{_duration(seconds)} / {_pct(percent)}", seconds, str(item.get("mode"))))
    command_basis = int((ce.get("improved_count", 0) or 0) + (ce.get("neutral_count", 0) or 0) + (ce.get("worse_count", 0) or 0))
    command_total = command_basis + int(ce.get("unknown_count", 0) or 0)
    html_parts = ["<div class='chartgrid'>"]
    html_parts.append(
        "<div class='chart-card'><h4>Abweichungsursachen</h4>"
        + _chart_info("Abweichungsursachen", "Prozentanteile der gewichteten Netzabweichung. Beeinflussbar bedeutet: Der Controller hatte in diesem Zustand grundsätzlich Stellmöglichkeit; nicht beeinflussbar umfasst z. B. SOC-, Leistungs-, Safe-State- oder Datenlimits.")
        + str(_bars_text([
            ("beeinflussbar", f"{_pct(fq.get('controllable_percent', 0))} der gewichteten Abweichung", fq.get("controllable_percent", 0), "Beeinflussbar"),
            ("nicht beeinflussbar", f"{_pct(fq.get('non_controllable_percent', 0))} der gewichteten Abweichung", fq.get("non_controllable_percent", 0), "Nicht beeinflussbar"),
        ])) + "</div>"
    )
    html_parts.append(
        "<div class='chart-card'><h4>Deadband</h4>"
        + _chart_info("Deadband", "Zeitanteile bezogen auf den analysierten Zeitraum. Deadband heißt: Der Regler soll bewusst ruhig bleiben, damit kleine Schwankungen nicht ständig neue MQTT-Kommandos auslösen.")
        + str(_bars_text([
            ("Deadband", f"{_duration(db.get('inside_deadband_seconds', 0))} / {_pct(db.get('inside_deadband_percent', 0))}", db.get("inside_deadband_percent", 0), "Deadband"),
            ("erweitert", f"{_duration(db.get('inside_extended_band_seconds', 0))} / {_pct(db.get('inside_extended_band_percent', 0))}", db.get("inside_extended_band_percent", 0), "Zeit im erweiterten Zielband"),
            ("außerhalb mit Reserve", f"{_duration(db.get('outside_deadband_with_reserve_seconds', 0))} / {_pct(db.get('outside_deadband_with_reserve_percent', 0))}", db.get("outside_deadband_with_reserve_percent", 0), "Außerhalb Deadband mit Reserve"),
        ])) + "</div>"
    )
    html_parts.append(
        "<div class='chart-card'><h4>Betriebszustände</h4>"
        + _chart_info("Betriebszustände", "Aufsummierte Zeit je abgeleitetem Betriebszustand. Die menschenlesbare Dauer und der Prozentanteil zeigen, wo der Controller den ausgewählten Zeitraum überwiegend verbracht hat.")
        + str(_bars_text(state_items)) + "</div>"
    )
    html_parts.append(
        "<div class='chart-card'><h4>MQTT-Wirkung</h4>"
        + _chart_info("MQTT-Wirkung", "Anzahl der MQTT-Kommandos nach grober Wirkung. Verbessert bedeutet: einige Zyklen später war die absolute Netzabweichung kleiner. Die Aussage ist ein Hinweis, kein Kausalbeweis, weil PV und Hauslast parallel schwanken können.")
        + str(_bars_text([
            ("verbessert", f"{_count(ce.get('improved_count', 0), 'Kommandos')} / {_pct(ce.get('improved_percent', 0))} der bewertbaren", ce.get("improved_count", 0), "verbessert"),
            ("neutral", f"{_count(ce.get('neutral_count', 0), 'Kommandos')} / {_pct(ce.get('no_effect_percent', 0))} der bewertbaren", ce.get("neutral_count", 0), "neutral"),
            ("verschlechtert", f"{_count(ce.get('worse_count', 0), 'Kommandos')} / {_pct(ce.get('worse_percent', 0))} der bewertbaren", ce.get("worse_count", 0), "verschlechtert"),
            ("nicht bewertbar", f"{_count(ce.get('unknown_count', 0), 'Kommandos')} / {_pct((float(ce.get('unknown_count', 0) or 0) / command_total * 100.0) if command_total else 0)} aller", ce.get("unknown_count", 0), "nicht bewertbar"),
        ]))
        + f"<p class='small'>Balkenbasis: absolute Anzahl Kommandos in diesem Block. Bewertbare Basis: {_count(command_basis, 'Kommandos')}; gesamt inklusive nicht bewertbar: {_count(command_total, 'Kommandos')}.</p></div>"
    )
    html_parts.append("</div>")
    return "".join(html_parts)

def text_report(result: Dict[str, Any]) -> str:
    fq = result.get("fair_regulator_quality") or {}; ce = result.get("command_efficiency") or {}; db = result.get("deadband") or {}
    lines = [
        f"Zendure Energy Controller CSV-Analyse V{REPORT_VERSION}", "============================================",
        f"Dateien: {', '.join(result.get('filenames') or [result.get('filename', '-')])}", f"Schema: {result.get('schema', '-')}",
        f"Datenzeilen: {result.get('rows', 0)}", f"Zeitraum: {result.get('period_start', '-')} bis {result.get('period_end', '-')}", f"Dauer: {_duration(result.get('duration_seconds', 0))}",
        "", "Kurzfazit / Empfehlungen", "------------------------",
    ]
    for rec in result.get("recommendations", []):
        lines.append(f"[{rec.get('severity','-')}] {rec.get('topic','-')}: {rec.get('text','-')}")
    lines += ["", "Faire Reglerqualität", "---------------------",
        f"Gesamt Ø |Netz|: {_w(fq.get('total_avg_abs_grid_w',0))}",
        f"Beeinflussbare Ø aktiv: {_w(fq.get('controllable_active_avg_abs_grid_w',0))}",
        f"Nicht beeinflussbarer Anteil: {_pct(fq.get('non_controllable_percent',0))}",
        f"Kompatibilität Ø |Netz|: {_w((result.get('regulator_quality') or {}).get('avg_abs_grid_w', fq.get('total_avg_abs_grid_w',0)))}",
        "", "Energiefluss", "------------",
        f"Netzbezug: {_kwh((result.get('energy') or {}).get('grid_import_kwh', result.get('grid_import_kwh', 0)))}",
        f"Netzeinspeisung: {_kwh((result.get('energy') or {}).get('grid_export_kwh', result.get('grid_export_kwh', 0)))}",
        f"Zendure geladen/entladen: {_kwh((result.get('energy') or {}).get('zendure_charge_kwh', 0))} / {_kwh((result.get('energy') or {}).get('zendure_discharge_kwh', 0))}",
        "", "Deadband / MQTT", "---------------",
        f"Zeit im Deadband: {_pct(db.get('inside_deadband_percent',0))}",
        f"Außerhalb Deadband mit Reserve: {_pct(db.get('outside_deadband_with_reserve_percent',0))}",
        f"MQTT-Kommandos gesamt: {ce.get('commands_total',0)}, pro aktiver Stunde: {_per_hour(ce.get('commands_per_active_hour',0))}",
        "", "Ereignisse", "----------",
    ]
    for event in result.get("events", [])[:80]:
        lines.append(f"{event.get('time', '-')}: [{event.get('severity', '-')}] {event.get('text', '-')}")
    if not result.get("events"):
        lines.append("keine auffälligen Ereignisse")
    return "\n".join(lines) + "\n"


# Compatibility wrapper for older replay_web/tests.
def html_table(result: Dict[str, Any]) -> str:
    return overview_table(result) + fair_regulator_table(result) + cross_charge_table(result)
