# SPDX-License-Identifier: AGPL-3.0-or-later
# Optional report helpers for Zendure Energy Controller CSV analysis.

import html
import json
import re
from typing import Any, Dict, Iterable, List, Tuple


class SafeHtml(str):
    """Small marker for trusted HTML snippets generated by this module."""


TERM_HELP: Dict[str, str] = {
    "Dateien": "CSV-Dateien, die in diesen Analyselauf eingeflossen sind. Die Analyse betrachtet nur diese Auswahl, nicht die gesamte Historie.",
    "Datenzeilen": "Anzahl ausgewerteter Messpunkte nach Schema- und Größenprüfung.",
    "Zeitraum": "Erster bis letzter Zeitstempel der ausgewerteten Messdaten.",
    "Dauer": "Zeitspanne zwischen erstem und letztem Messpunkt.",
    "Datenqualität": "Gesamtbewertung der Verwendbarkeit der ausgewählten Messdaten für die Analyse.",
    "Status": "Kurzbewertung der Datenqualität. Warnungen werden separat aufgeführt.",
    "Datenlücken": "Anzahl erkannter größerer Zeitabstände zwischen Messpunkten.",
    "Fehlende Netzwerte": "Messpunkte ohne auswertbare Netzleistung. Diese Werte sind für die Reglerqualitätsbewertung kritisch.",
    "Fehlende SOC-Werte": "Messpunkte ohne Zendure-SOC. SOC-bezogene Auswertungen sind dann nur eingeschränkt belastbar.",
    "Fehlende Zendure-Istwerte": "Messpunkte ohne reale Zendure-Istleistung. Soll-/Ist-Vergleiche sind dann eingeschränkt.",
    "SAFE_STATE-Zeit": "Ausgewertete Zeit, in der der Controller laut CSV im Safe-State war.",
    "Netzbezug": "Aus positiver Netzleistung integrierte Energie. Bezieht sich nur auf die ausgewählten CSV-Dateien.",
    "Netzeinspeisung": "Aus negativer Netzleistung integrierte Energie. Bezieht sich nur auf die ausgewählten CSV-Dateien.",
    "Zendure geladen": "Aus positiver signierter Zendure-Istleistung berechnete Ladeenergie.",
    "Zendure entladen": "Aus negativer signierter Zendure-Istleistung berechnete Entladeenergie.",
    "Zusatzbatterie geladen": "Aus positiver Zusatzbatterie-Leistung berechnete Ladeenergie, sofern die Werte vorhanden sind.",
    "Zusatzbatterie entladen": "Aus negativer Zusatzbatterie-Leistung berechnete Entladeenergie, sofern die Werte vorhanden sind.",
    "Gesamte Ø |Netz|": "Mittlere absolute Netzabweichung über den gesamten Analysezeitraum. Enthält auch volle Batterie, Safe-State und Leistungsgrenzen und ist daher keine reine Reglerbewertung.",
    "Regelbares Zeitfenster": "Zeitanteil, in dem der Controller grundsätzlich eine sinnvolle Stellmöglichkeit hatte oder das Netz bereits im Zielband lag.",
    "Beeinflussbare Ø Restabweichung": "Nur der Anteil der Netzabweichung, der nach verfügbarer Lade-/Entladereserve theoretisch beeinflussbar war.",
    "Beeinflussbare Ø aktiv": "Beeinflussbare Restabweichung bezogen auf das aktive Regelfenster. Diese Kennzahl ist die fairere Reglerqualitätsgröße.",
    "Nicht beeinflussbare Ø Abweichung": "Abweichungsanteil, der wegen SOC-/Leistungsgrenzen, Safe-State oder fehlender Stellreserve nicht vom Regler beseitigt werden konnte.",
    "Nicht beeinflussbarer Anteil": "Anteil der gewichteten Gesamtabweichung, der in diesem Analyselauf nicht sinnvoll dem Regleralgorithmus zugerechnet werden sollte.",
    "Ladelimit-Zeit": "Zeit mit Einspeisung, in der keine oder fast keine zusätzliche Ladereserve verfügbar war.",
    "Entladelimit-Zeit": "Zeit mit Netzbezug, in der keine oder fast keine zusätzliche Entladereserve verfügbar war.",
    "Ø freie Ladereserve": "Durchschnittlich verfügbare zusätzliche Ladeleistung während einspeisender Phasen mit vorhandener Stellreserve.",
    "Ø freie Entladereserve": "Durchschnittlich verfügbare zusätzliche Entladeleistung während bezugslastiger Phasen mit vorhandener Stellreserve.",
    "Ø Soll/Ist-Abweichung": "Mittlere Differenz zwischen signierter Zendure-Sollleistung und signierter Istleistung bei aktiver Anforderung.",
    "Ziel gut erreicht": "Zeitanteil, in dem Zendure dem Sollwert innerhalb einer tolerierten Abweichung folgte.",
    "Ziel deutlich verfehlt": "Zeitanteil, in dem die Soll-/Ist-Abweichung deutlich erhöht war.",
    "Anforderung ohne Reaktion": "Zeit mit relevanter Lade- oder Entladeanforderung, aber kaum entsprechender Zendure-Istleistung.",
    "Sollwert-Richtungswechsel": "Anzahl der Vorzeichenwechsel des Sollwerts zwischen Laden und Entladen. Viele Wechsel können auf Oszillation hinweisen.",
    "Kurze Gegenbefehle": "Richtungswechsel innerhalb kurzer Zeit. Das kann auf eine zu aggressive oder zu wenig gedämpfte Regelung hinweisen.",
    "Große Sollwertsprünge": "Anzahl großer Änderungen des Sollwerts. Einzelne Sprünge können normal sein, viele Sprünge deuten auf unruhige Regelung.",
    "Schwingungsbewertung": "Verdichtete Bewertung der Oszillationsindikatoren.",
    "Zeit im Deadband": "Anteil der Zeit, in der die Netzleistung innerhalb des konfigurierten Deadbands lag.",
    "Zeit im erweiterten Zielband": "Anteil der Zeit in einem größeren Zielbereich um 0 W. Hilft, die praktische Regelruhe zu bewerten.",
    "HOLD korrekt im Deadband": "Zeitanteil, in dem der Regler im Deadband sinnvoll keine Stelländerung vorgenommen hat.",
    "Außerhalb Deadband mit Reserve": "Zeit außerhalb des Deadbands, obwohl noch Stellreserve vorhanden war. Das ist ein Kandidat für echte Reglerabweichung.",
    "Kommandos im Deadband": "MQTT-Kommandos, obwohl das Netz bereits im Deadband lag. Viele davon können unnötige Unruhe bedeuten.",
    "MQTT-Kommandos gesamt": "Anzahl gesendeter MQTT-Befehle im Analysezeitraum.",
    "Kommandos pro aktiver Regelstunde": "MQTT-Kommandos bezogen auf das aktive Regelfenster, nicht auf den gesamten Logzeitraum.",
    "Erkennbare Verbesserung": "Anteil bewertbarer Kommandos, nach denen die absolute Netzabweichung wenige Zyklen später kleiner war. Diese Diagnose ist grob, da Last/PV parallel schwanken.",
    "Keine erkennbare Wirkung": "Anteil bewertbarer Kommandos ohne deutliche Verbesserung oder Verschlechterung wenige Zyklen später.",
    "Ampel": "Verdichtete Cross-Charge-Bewertung: grün unauffällig, gelb kurze/geringe Überschneidungen, rot deutliche kritische Überschneidungen.",
    "Bewertung": "Textliche Begründung für die Ampelfarbe.",
    "Blockade-Ereignisse": "Anzahl erkannter Phasen, in denen Cross-Charge-Begrenzungen oder -Blockaden aktiv waren.",
    "Blockade-Zeit": "Gesamtdauer der erkannten Cross-Charge-Blockadephasen.",
    "Kritische Überschneidungen": "Phasen, in denen die Zusatzbatterie entlädt, während Zendure gleichzeitig lädt.",
    "Zeit bei MIN_SOC": "Zeit, in der der Zendure-SOC am unteren konfigurierten Grenzwert lag.",
    "Zeit bei MAX_SOC": "Zeit, in der der Zendure-SOC am oberen konfigurierten Grenzwert lag.",
    "High-SOC-Ladeannahme": "Verteilung der einfachen Ladeannahme-Diagnosezustände. V12.8.4 wertet diesen Bereich nur leichtgewichtig aus.",
    "Zustand": "Abgeleiteter Betriebszustand für die Matrix. Er trennt regelbare und nicht regelbare Phasen besser als der reine technische Modus.",
    "Samples": "Anzahl der Messpunkte, die dieser Zeile zugeordnet wurden.",
    "Zeit": "Aus dt_s aufsummierte Dauer für diese Gruppe oder dieses Ereignis.",
    "Zielband": "Anteil der Zeit, in der die Netzleistung innerhalb des Zielbandes um 0 W lag.",
    "MQTT": "Anzahl der in diesem Bereich gesendeten MQTT-Kommandos.",
    "Schwere": "Einordnung des Ereignisses, z. B. Info, Warnung oder kritisch.",
    "Typ": "Technische Ereigniskategorie für Filterung und spätere Auswertung.",
    "Ereignis": "Lesbare Beschreibung der erkannten Auffälligkeit oder Zustandsänderung.",
}

try:
    from version import APP_VERSION as REPORT_VERSION
except Exception:  # pragma: no cover
    REPORT_VERSION = "12.8.4"


def _duration(seconds: float) -> str:
    seconds = int(float(seconds or 0))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h} h {m:02d} min"
    if m:
        return f"{m} min {s:02d} s"
    return f"{s} s"


def _format_de_number(value: Any, digits: int = 1, *, trim: bool = True) -> str:
    if value in (None, ""):
        return "-"
    try:
        number = float(value)
    except Exception:
        return str(value)
    text = f"{number:,.{max(0, digits)}f}"
    if trim and digits > 0:
        text = text.rstrip("0").rstrip(".")
    return text.replace(",", "X").replace(".", ",").replace("X", ".")


def _num(value: Any, suffix: str = "", digits: int = 1, *, trim: bool = True) -> str:
    return f"{_format_de_number(value, digits, trim=trim)}{suffix}"


def _kwh(value: Any) -> str: return _num(value, " kWh", 4, trim=False)
def _w(value: Any) -> str: return _num(value, " W", 1, trim=True)
def _pct(value: Any) -> str: return _num(value, " %", 1, trim=True)
def _per_hour(value: Any) -> str: return _num(value, " / h", 1, trim=True)


def _states_summary(states: Dict[str, Any]) -> str:
    order = ["ok", "suspect", "limited", "not_accepting"]
    labels = {"ok": "ok", "suspect": "Verdacht", "limited": "begrenzt", "not_accepting": "nimmt nicht an"}
    parts = [f"{labels[k]}: {states.get(k, 0)}" for k in order if k in states]
    parts += [f"{k}: {states.get(k, 0)}" for k in sorted(k for k in states if k not in order)]
    return ", ".join(parts) if parts else "keine Daten"


def _stringify_mapping(value: Dict[str, Any]) -> str:
    if set(value.keys()) & {"ok", "suspect", "limited", "not_accepting"}:
        return _states_summary(value)
    return ", ".join(f"{key}: {val}" for key, val in sorted(value.items()))


def _label_cell(label: str) -> SafeHtml:
    label_text = str(label)
    help_text = TERM_HELP.get(label_text)
    escaped = html.escape(label_text)
    if not help_text:
        return SafeHtml(escaped)
    return SafeHtml(f"<span>{escaped}</span> <details class='term-info'><summary>info</summary><div>{html.escape(help_text)}</div></details>")


def _cell(value: Any) -> str:
    if isinstance(value, SafeHtml):
        return str(value)
    if isinstance(value, dict):
        return html.escape(_stringify_mapping(value))
    if isinstance(value, (list, tuple)):
        return html.escape(", ".join(_stringify_mapping(v) if isinstance(v, dict) else str(v) for v in value))
    return html.escape(str(value))


def _table(rows: Iterable[Tuple[str, Any]]) -> str:
    return "".join(f"<tr><th>{_label_cell(str(label))}</th><td>{_cell(value)}</td></tr>" for label, value in rows)


def _th(label: str) -> str: return str(_label_cell(label))


def _rating_badge(value: str) -> SafeHtml:
    cls = {"green": "ok", "yellow": "warn", "red": "bad", "ok": "ok", "warning": "warn", "error": "bad"}.get(value, "neutral")
    label = {"green": "grün", "yellow": "gelb", "red": "rot", "ok": "ok", "warning": "Warnung", "error": "Fehler"}.get(value, value)
    return SafeHtml(f"<span class='badge {cls}'>{html.escape(label)}</span>")


def _bar(label: str, value: float, max_value: float, css: str = "bar") -> SafeHtml:
    width = 0 if max_value <= 0 else max(0.0, min(100.0, float(value) / max_value * 100.0))
    return SafeHtml(f"<div class='barrow'><span>{html.escape(label)}</span><div class='barbox'><div class='{css}' style='width:{width:.1f}%'></div></div><b>{_format_de_number(value, 1)}</b></div>")


def _bars(items: List[Tuple[str, float]], css: str = "bar") -> SafeHtml:
    if not items:
        return SafeHtml("<p>Keine Diagrammdaten.</p>")
    max_value = max([abs(float(v or 0)) for _, v in items] + [1.0])
    return SafeHtml("".join(str(_bar(label, float(value or 0), max_value, css)) for label, value in items))


def summary_cards(result: Dict[str, Any]) -> str:
    ratings = result.get("summary_ratings") or {}
    labels = [
        ("fair_regulator_quality", "Reglerqualität"), ("actuator_reserve", "Stellreserve"),
        ("zendure_tracking", "Soll/Ist"), ("deadband", "Deadband"),
        ("mqtt_command_effect", "MQTT-Wirkung"), ("oscillation", "Oszillation"),
        ("cross_charge", "Cross-Charge"), ("data_quality", "Datenqualität"),
    ]
    cards = []
    for key, label in labels:
        cards.append(f"<div class='card'><div>{html.escape(label)}</div>{_rating_badge(str(ratings.get(key, '-')))}</div>")
    return "".join(cards)


def recommendations_table(result: Dict[str, Any]) -> str:
    recs = result.get("recommendations") or []
    if not recs:
        return "<tr><td>Keine Empfehlungen erzeugt.</td></tr>"
    rows = f"<tr><th>{_th('Schwere')}</th><th>Thema</th><th>Empfehlung</th></tr>"
    for rec in recs:
        rows += f"<tr><td>{_rating_badge(str(rec.get('severity','neutral')))}</td><td>{html.escape(str(rec.get('topic','-')))}</td><td>{html.escape(str(rec.get('text','-')))}</td></tr>"
    return rows


def overview_table(result: Dict[str, Any]) -> str:
    dq = result.get("data_quality") or {}
    return _table([
        ("Dateien", ", ".join(result.get("filenames") or [result.get("filename", "-")])),
        ("Datenzeilen", result.get("rows", 0)),
        ("Zeitraum", f"{result.get('period_start', '-')} bis {result.get('period_end', '-')}"),
        ("Dauer", _duration(result.get("duration_seconds", 0))),
        ("Datenqualität", _rating_badge("green" if dq.get("status") == "ok" else ("red" if dq.get("status") == "error" else "yellow"))),
        ("Ø / Median / max dt_s", f"{_num(dq.get('avg_dt_s', 0), '', 3)} / {_num(dq.get('median_dt_s', 0), '', 3)} / {_num(dq.get('max_dt_s', 0), ' s', 3)}"),
    ])


def data_quality_table(result: Dict[str, Any]) -> str:
    dq = result.get("data_quality") or {}
    warnings = dq.get("warnings") or []
    warning_html = SafeHtml("<br>".join(html.escape(str(w)) for w in warnings)) if warnings else "keine"
    return _table([
        ("Status", dq.get("status", "-")), ("Datenlücken", dq.get("gap_events", 0)),
        ("Fehlende Netzwerte", dq.get("missing_grid_rows", 0)), ("Fehlende SOC-Werte", dq.get("missing_soc_rows", 0)),
        ("Fehlende Zendure-Istwerte", dq.get("missing_zendure_actual_rows", 0)), ("SAFE_STATE-Zeit", _duration(dq.get("safe_state_seconds", 0))),
        ("Hinweise", warning_html),
    ])


def energy_table(result: Dict[str, Any]) -> str:
    e = result.get("energy") or {}
    return _table([
        ("Netzbezug", _kwh(e.get('grid_import_kwh', result.get('grid_import_kwh', 0)))),
        ("Netzeinspeisung", _kwh(e.get('grid_export_kwh', result.get('grid_export_kwh', 0)))),
        ("Zendure geladen", _kwh(e.get('zendure_charge_kwh', 0))), ("Zendure entladen", _kwh(e.get('zendure_discharge_kwh', 0))),
        ("Zusatzbatterie geladen", _kwh(e.get('second_battery_charge_kwh', 0))), ("Zusatzbatterie entladen", _kwh(e.get('second_battery_discharge_kwh', 0))),
    ])


def fair_regulator_table(result: Dict[str, Any]) -> str:
    fq = result.get("fair_regulator_quality") or {}
    return _table([
        ("Ampel", _rating_badge(str(fq.get("rating", "-")))),
        ("Gesamte Ø |Netz|", _w(fq.get("total_avg_abs_grid_w", 0))),
        ("Regelbares Zeitfenster", f"{_duration(fq.get('active_window_seconds', 0))} ({_pct(fq.get('active_window_percent', 0))})"),
        ("Beeinflussbare Ø Restabweichung", _w(fq.get("controllable_avg_abs_grid_w", 0))),
        ("Beeinflussbare Ø aktiv", _w(fq.get("controllable_active_avg_abs_grid_w", 0))),
        ("Nicht beeinflussbare Ø Abweichung", _w(fq.get("non_controllable_avg_abs_grid_w", 0))),
        ("Nicht beeinflussbarer Anteil", _pct(fq.get("non_controllable_percent", 0))),
    ])


def actuator_table(result: Dict[str, Any]) -> str:
    ar = result.get("actuator_reserve") or {}
    return _table([
        ("Ampel", _rating_badge(str(ar.get("rating", "-")))),
        ("Ladelimit-Zeit", f"{_duration(ar.get('charge_saturated_seconds', 0))} ({_pct(ar.get('charge_saturated_percent', 0))})"),
        ("Entladelimit-Zeit", f"{_duration(ar.get('discharge_saturated_seconds', 0))} ({_pct(ar.get('discharge_saturated_percent', 0))})"),
        ("Ø freie Ladereserve", _w(ar.get("avg_free_charge_reserve_w", 0))),
        ("Ø freie Entladereserve", _w(ar.get("avg_free_discharge_reserve_w", 0))),
    ])


def tracking_table(result: Dict[str, Any]) -> str:
    tr = result.get("tracking") or {}
    return _table([
        ("Ampel", _rating_badge(str(tr.get("rating", "-")))),
        ("Ø Soll/Ist-Abweichung", _w(tr.get("avg_error_w", 0))),
        ("95%-Perzentil |Netz|", _w(tr.get("p95_error_w", 0))),
        ("Ziel gut erreicht", _pct(tr.get("good_tracking_percent", 0))),
        ("Ziel deutlich verfehlt", _pct(tr.get("bad_tracking_percent", 0))),
        ("Anforderung ohne Reaktion", _duration(tr.get("target_without_actual_seconds", 0))),
    ])


def oscillation_table(result: Dict[str, Any]) -> str:
    osc = result.get("oscillation") or {}
    return _table([
        ("Schwingungsbewertung", _rating_badge(str(osc.get("rating", "-")))),
        ("Sollwert-Richtungswechsel", osc.get("target_sign_changes", 0)),
        ("Kurze Gegenbefehle", osc.get("short_reverse_commands", 0)),
        ("Große Sollwertsprünge", osc.get("large_target_steps", 0)),
        ("Moduswechsel", f"{osc.get('mode_switches', 0)} ({_per_hour(osc.get('mode_switches_per_hour', 0))})"),
    ])


def deadband_table(result: Dict[str, Any]) -> str:
    db = result.get("deadband") or {}
    return _table([
        ("Ampel", _rating_badge(str(db.get("rating", "-")))),
        ("Zeit im Deadband", f"{_duration(db.get('inside_deadband_seconds', 0))} ({_pct(db.get('inside_deadband_percent', 0))})"),
        ("Zeit im erweiterten Zielband", _pct(db.get("inside_extended_band_percent", 0))),
        ("HOLD korrekt im Deadband", _pct(db.get("hold_inside_deadband_percent", 0))),
        ("Außerhalb Deadband mit Reserve", f"{_duration(db.get('outside_deadband_with_reserve_seconds', 0))} ({_pct(db.get('outside_deadband_with_reserve_percent', 0))})"),
        ("Kommandos im Deadband", db.get("commands_inside_deadband", 0)),
    ])


def command_efficiency_table(result: Dict[str, Any]) -> str:
    ce = result.get("command_efficiency") or {}
    return _table([
        ("Ampel", _rating_badge(str(ce.get("rating", "-")))),
        ("MQTT-Kommandos gesamt", ce.get("commands_total", 0)),
        ("Kommandos pro aktiver Regelstunde", _per_hour(ce.get("commands_per_active_hour", 0))),
        ("Ø / max Sollwertsprung", f"{_w(ce.get('avg_target_step_w', 0))} / {_w(ce.get('max_target_step_w', 0))}"),
        ("Erkennbare Verbesserung", f"{ce.get('improved_count', 0)} ({_pct(ce.get('improved_percent', 0))})"),
        ("Keine erkennbare Wirkung", f"{ce.get('neutral_count', 0)} ({_pct(ce.get('no_effect_percent', 0))})"),
        ("Nicht bewertbar", ce.get("unknown_count", 0)),
    ])


def regulator_table(result: Dict[str, Any]) -> str:
    # Compatibility: keep the old table name, but use the new fair view.
    return fair_regulator_table(result)


def cross_charge_table(result: Dict[str, Any]) -> str:
    cq = result.get("cross_charge") or {}
    return _table([
        ("Ampel", _rating_badge(str(cq.get("rating", "-")))), ("Bewertung", cq.get("rating_reason", "-")),
        ("Blockade-Ereignisse", cq.get("block_events", 0)), ("Blockade-Zeit", _duration(cq.get("blocked_seconds", 0))),
        ("Kritische Überschneidungen", cq.get("critical_overlap_events", 0)),
        ("Kritische Überschneidungszeit", _duration(cq.get("critical_overlap_seconds", 0))),
        ("Max. SMA-Entladung während Überschneidung", _w(cq.get('max_sma_discharge_w_during_overlap', 0))),
        ("Ø SMA-Entladung während Überschneidung", _w(cq.get('avg_sma_discharge_w_during_overlap', 0))),
        ("Max. Zendure-Ladung während Überschneidung", _w(cq.get('max_zendure_charge_w_during_overlap', 0))),
        ("Verhinderte/reduzierte Ladeenergie grob", _kwh(cq.get('reduced_or_prevented_charge_kwh', 0))),
    ])


def mode_quality_table(result: Dict[str, Any]) -> str:
    rows = f"<tr><th>{_th('Zustand')}</th><th>{_th('Samples')}</th><th>{_th('Zeit')}</th><th>Import</th><th>Export</th><th>Ø |Netz|</th><th>Beeinflussbar Ø</th><th>Nicht beeinflussbar Ø</th><th>{_th('Zielband')}</th><th>{_th('MQTT')}</th></tr>"
    for item in result.get("operating_state_matrix") or result.get("mode_quality") or []:
        rows += (
            f"<tr><td>{html.escape(str(item.get('mode')))}</td><td>{item.get('samples')}</td><td>{_duration(item.get('seconds', 0))} ({_pct(item.get('percent', 0))})</td>"
            f"<td>{_kwh(item.get('grid_import_kwh', 0))}</td><td>{_kwh(item.get('grid_export_kwh', 0))}</td><td>{_w(item.get('avg_abs_grid_w'))}</td>"
            f"<td>{_w(item.get('controllable_avg_abs_grid_w', 0))}</td><td>{_w(item.get('non_controllable_avg_abs_grid_w', 0))}</td>"
            f"<td>{_pct(item.get('time_in_target_band_percent'))}</td><td>{item.get('mqtt_commands')}</td></tr>"
        )
    return rows


def high_soc_table(result: Dict[str, Any]) -> str:
    states = result.get("charge_acceptance_states") or {}
    return _table([
        ("Zeit bei MIN_SOC", _duration(result.get("time_at_min_soc_seconds", 0))),
        ("Zeit bei MAX_SOC", _duration(result.get("time_at_max_soc_seconds", 0))),
        ("High-SOC-Ladeannahme", _states_summary(states)),
        ("Einordnung", "V12.8.4 zählt High-SOC nur leichtgewichtig; Schwerpunkt sind faire Reglerqualität, Stellreserve und Cross-Charge."),
    ])


def events_table(result: Dict[str, Any], limit: int = 120) -> str:
    events: List[Dict[str, Any]] = list(result.get("events") or [])[:limit]
    if not events:
        return "<tr><td>Keine auffälligen Ereignisse erkannt.</td></tr>"
    rows = f"<tr><th>{_th('Zeit')}</th><th>{_th('Schwere')}</th><th>{_th('Typ')}</th><th>{_th('Ereignis')}</th></tr>"
    for event in events:
        rows += f"<tr><td>{html.escape(str(event.get('time', '-')))}</td><td>{html.escape(str(event.get('severity', '-')))}</td><td>{html.escape(str(event.get('type', '-')))}</td><td>{html.escape(str(event.get('text', '-')))}</td></tr>"
    return rows


def charts_html(result: Dict[str, Any]) -> str:
    fq = result.get("fair_regulator_quality") or {}
    db = result.get("deadband") or {}
    ce = result.get("command_efficiency") or {}
    state_items = [(str(i.get("mode")), float(i.get("seconds", 0))) for i in (result.get("operating_state_matrix") or [])[:8]]
    html_parts = [
        "<div class='chartgrid'>",
        "<div><h4>Abweichungsursachen</h4>" + str(_bars([("beeinflussbar", fq.get("controllable_percent", 0)), ("nicht beeinflussbar", fq.get("non_controllable_percent", 0))], "bar")) + "</div>",
        "<div><h4>Deadband</h4>" + str(_bars([("Deadband", db.get("inside_deadband_percent", 0)), ("erweitert", db.get("inside_extended_band_percent", 0)), ("außerhalb mit Reserve", db.get("outside_deadband_with_reserve_percent", 0))], "bar")) + "</div>",
        "<div><h4>Betriebszustände</h4>" + str(_bars(state_items, "bar")) + "</div>",
        "<div><h4>MQTT-Wirkung</h4>" + str(_bars([("verbessert", ce.get("improved_count", 0)), ("neutral", ce.get("neutral_count", 0)), ("verschlechtert", ce.get("worse_count", 0)), ("nicht bewertbar", ce.get("unknown_count", 0))], "bar")) + "</div>",
        "</div>",
    ]
    return "".join(html_parts)


def text_report(result: Dict[str, Any]) -> str:
    fq = result.get("fair_regulator_quality") or {}; ce = result.get("command_efficiency") or {}; db = result.get("deadband") or {}
    lines = [
        f"Zendure Energy Controller CSV-Analyse V{REPORT_VERSION}", "============================================",
        f"Dateien: {', '.join(result.get('filenames') or [result.get('filename', '-')])}", f"Schema: {result.get('schema', '-')}",
        f"Datenzeilen: {result.get('rows', 0)}", f"Zeitraum: {result.get('period_start', '-')} bis {result.get('period_end', '-')}", f"Dauer: {_duration(result.get('duration_seconds', 0))}",
        "", "Kurzfazit / Empfehlungen", "------------------------",
    ]
    for rec in result.get("recommendations", []):
        lines.append(f"[{rec.get('severity','-')}] {rec.get('topic','-')}: {rec.get('text','-')}")
    lines += ["", "Faire Reglerqualität", "---------------------",
        f"Gesamt Ø |Netz|: {_w(fq.get('total_avg_abs_grid_w',0))}",
        f"Beeinflussbare Ø aktiv: {_w(fq.get('controllable_active_avg_abs_grid_w',0))}",
        f"Nicht beeinflussbarer Anteil: {_pct(fq.get('non_controllable_percent',0))}",
        f"Kompatibilität Ø |Netz|: {_w((result.get('regulator_quality') or {}).get('avg_abs_grid_w', fq.get('total_avg_abs_grid_w',0)))}",
        "", "Energiefluss", "------------",
        f"Netzbezug: {_kwh((result.get('energy') or {}).get('grid_import_kwh', result.get('grid_import_kwh', 0)))}",
        f"Netzeinspeisung: {_kwh((result.get('energy') or {}).get('grid_export_kwh', result.get('grid_export_kwh', 0)))}",
        f"Zendure geladen/entladen: {_kwh((result.get('energy') or {}).get('zendure_charge_kwh', 0))} / {_kwh((result.get('energy') or {}).get('zendure_discharge_kwh', 0))}",
        "", "Deadband / MQTT", "---------------",
        f"Zeit im Deadband: {_pct(db.get('inside_deadband_percent',0))}",
        f"Außerhalb Deadband mit Reserve: {_pct(db.get('outside_deadband_with_reserve_percent',0))}",
        f"MQTT-Kommandos gesamt: {ce.get('commands_total',0)}, pro aktiver Stunde: {_per_hour(ce.get('commands_per_active_hour',0))}",
        "", "Ereignisse", "----------",
    ]
    for event in result.get("events", [])[:80]:
        lines.append(f"{event.get('time', '-')}: [{event.get('severity', '-')}] {event.get('text', '-')}")
    if not result.get("events"):
        lines.append("keine auffälligen Ereignisse")
    return "\n".join(lines) + "\n"


# Compatibility wrapper for older replay_web/tests.
def html_table(result: Dict[str, Any]) -> str:
    return overview_table(result) + fair_regulator_table(result) + cross_charge_table(result)
